# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b53ec4f448e06aa07f4d952f9ecc5fcdabe61d224b2c8c7ffb289dc0a6b49ffb96cb4a3bcfbffa0791cf25e2cbaf4a0364ea60bde98e6dd6d1519883b2ba167

test:
  secret_key_base: 46c2e6f3592cc7a6981a7eb656397397b6306a08a3a7dea1001a816ebf2b70d7a4d77e48785993f3ddfc10dec8b7afefb9b9633706a45863ccf2f2b10a7640ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
